# -*- coding: utf-8 -*-
"""business-it-workshop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tfxzjvovdhpV2E4giME97p6-dH2-TbDq
"""

import requests
from datetime import datetime
import pandas as pd
from bs4 import BeautifulSoup

base_url = "https://quotes.toscrape.com/"
all_quotes_data = []
current_url = base_url

while True:
    response = requests.get(current_url, timeout=20)
    response.encoding = "utf-8"
    soup = BeautifulSoup(response.text, "html.parser")

    for item in soup.select(".quote"):
        _quote = item.select_one(".text")
        _author = item.select_one(".author")
        _tags = item.select(".tag") # Select all elements with class 'tag'

        scrape_time = datetime.now().isoformat()

        quote = _quote.get_text() if _quote else None
        author = _author.get_text() if _author else None
        # Extract tag text and join them with a comma, or set to None if no tags
        tags = [tag.get_text(strip=True) for tag in _tags] if _tags else None

        all_quotes_data.append({
            "Quotes": quote,
            "Author": author,
            "Tags": tags, # Add the extracted tags
            "scraped_at": scrape_time
        })

    next_button = soup.select_one("li.next a")
    if next_button:
        next_page_relative_url = next_button["href"]
        current_url = base_url + next_page_relative_url
    else:
        break # No next button, so we have scraped all pages

df = pd.DataFrame(all_quotes_data)
display(df)





# Replace your existing df.to_csv() line with this:
import os

filename = "my_dataset.csv"

if os.path.exists(filename):
    # File already exists → append without writing headers again
    df.to_csv(filename, mode="a", header=False, index=False)
else:
    # First run → create file with headers
    df.to_csv(filename, index=False)

import requests
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime

from supabase import create_client
from datetime import datetime

import os

SUPABASE_URL = os.environ["SUPABASE_URL"]
SUPABASE_KEY = os.environ["SUPABASE_KEY"]

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

scrape_time = datetime.now().isoformat()

rows = []
for _, row in df.iterrows():
    # Get the list of tags for the current quote
    current_quote_tags = row.get("Tags", [])
    # Join the tags with a comma and space, or set to None if no tags
    tags_string = ", ".join(current_quote_tags) if current_quote_tags else None

    rows.append({
        "quote": str(row.get("Quotes", "")),
        "author": str(row.get("Author", "")),
        "tags": tags_string
    })

result = supabase.table("quotes").insert(rows).execute()